<?php
class Tic9543UpdateHelpContent extends Migration
{
    public function description()
    {
        return 'update english help_content entries';
    }

    public function up()
    {
        $db = DBManager::get();
        $db->exec("UPDATE `help_content` SET `content` = 'You can find university ressources like rooms, buildings etc. with the ressource search engine.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = 'e206a4257e31a0f32ac516cefb8e8331'");
        $db->exec("UPDATE `help_content` SET `content` = 'In the default substitution settings, lecturers can specify a default substitution that can manage and change all of the lecturer''s courses.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '85c000e33732c5596d198776cb884860'");
        $db->exec("UPDATE `help_content` SET `content` = 'The overview contains course-related short and detailed information, announcements, dates and surveys.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = 'd97eff1196f6aed8e94f7c5096ebd2a9'");
        $db->exec("UPDATE `help_content` SET `content` = 'Here you can add further features to the course.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '852991dc733639dd2df05fb627abf3db'");
        $db->exec("UPDATE `help_content` SET `content` = 'Here, individual content can be activated or deactivated. Active contents add new features to your profile or settings. These will usually appear as new tabs in the menu. If features are not required, they can be deactivated here. The corresponding menu items will then be hidden.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = 'b5fabb1e5aed7ff8520314e9a86c5c87'");
        $db->exec("UPDATE `help_content` SET `content` = 'With the user search, users can be found as long as their privacy settings do not prevent this. The search can be limited to certain courses or institutions.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = 'ebcc460880b8a63af3f6e7eade97db78'");
        $db->exec("UPDATE `help_content` SET `content` = 'Here you can find an overview of the dates that have been booked by students.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '0ad754cc62d1e86e97c1a28dd68ac40c'");
        $db->exec("UPDATE `help_content` SET `content` = 'The forum is a text-based, time- and location-independent platform for the exchange of questions, opinions and experiences. Contributions can be subscribed to, exported, marked as favourites and edited. The navigation on the left allows you to select different views (e.g. New posts since last login).', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '80286432bf17df20e5f11f86b421b0a7'");
        $db->exec("UPDATE `help_content` SET `content` = 'You can use the fields of study-feature to assign a course to a field of study. Editing can be locked if data is transferred from other systems (for example, LSF/ UniVZ).', `studip_version` = '4.4' WHERE `help_content`.`content_id` = 'eec46c5d8ea5523d959a8c334455c2ef'");
        $db->exec("UPDATE `help_content` SET `content` = 'With access authorisation (enrolment procedure), access to a course can be regulated e.g. by means of passwords, time control and participant restrictions.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '4e14c94cda99e2ef6462f7fef06d9c91'");
        $db->exec("UPDATE `help_content` SET `content` = 'The start page opens after logging in and can be adjusted to your personal needs by using widgets.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = 'b05b27450e363c38c6b4620b902b3496'");
        $db->exec("UPDATE `help_content` SET `content` = 'Detailed information about the course, e.g. the course number, assignments, lecturers, tutors, etc. is displayed. In the detail information, you can enter a course under Actions.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '357bbf06015b2738aae15837f581a07d'");
        $db->exec("UPDATE `help_content` SET `content` = 'In the notification settings you can select which changes within a course you want to be notified for.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '43df8e33145c25eb6d941e4e845ada24'");
        $db->exec("UPDATE `help_content` SET `content` = 'Here you can add members to a study group and send messages to them.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = 'b3bd33cb0babbb0cc51a4f429d15d438'");
        $db->exec("UPDATE `help_content` SET `content` = 'This page shows the institutions that the user is assigned to.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '438c4456f85afec29fd9f47c111136c1'");
        $db->exec("UPDATE `help_content` SET `content` = 'View of the institutions assigned to the Stud.IP user.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = 'd04ca1f9e867ee295a3025dac7ce9c7b'");
        $db->exec("UPDATE `help_content` SET `content` = 'This page offers the possibility to enter Stud.IP users in your own address book and to list all contacts already in the address book.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '27c4d9837cfb1a9a40c079e16daac902'");
        $db->exec("UPDATE `help_content` SET `content` = 'Individual user data e.g. email address, can be changed on this page.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = 'fe23b56f4d691c0f5e2f872e37ce38b5'");
        $db->exec("UPDATE `help_content` SET `content` = 'The evaluation function can be used to create surveys with multiple-choice, and free text questions for courses, study groups, your own profile or institutions. Other people''s public templates can also be used. All future, current and completed evaluations are displayed.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '5475d65b07fdaf5f234bf6eed3d5e4a9'");
        $db->exec("UPDATE `help_content` SET `content` = 'The schedule shows dates, topics and rooms of the course. Individual dates can be edited, for example, topics can be added to dates.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '8c3067596811d3c6857d253299e01f6f'");
        $db->exec("UPDATE `help_content` SET `content` = 'Here you can edit reference lists and make them visible in a course (click on the \"eye\").', `studip_version` = '4.4' WHERE `help_content`.`content_id` = 'fa4bf491690645a5f12556f77e51233c'");
        $db->exec("UPDATE `help_content` SET `content` = 'Possibility of providing lecture recordings and podcasts for students of the course (by linking to the files on the media server).', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '7465a4aeedb6a320d3455cf9ad0bebd0'");
        $db->exec("UPDATE `help_content` SET `content` = 'The timetable consists of courses you have subscribed to, which can be shown and hidden as well as adjusted in display size and form.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '440e50f7fcc825368aa9026273d2cd0d'");
        $db->exec("UPDATE `help_content` SET `content` = 'On this page you can see which contacts are currently online. A message can be sent to these people. Clicking on a person''s name will take you to their profile.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '2f1602394a4e31c2e30706f0a0b3112f'");
        $db->exec("UPDATE `help_content` SET `content` = 'Date allocation can be used to create appointments for consultation hours, exams, etc. in which students can enter themselves.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '5ae72abc0822570bfe839e3ee24f0c81'");
        $db->exec("UPDATE `help_content` SET `content` = 'Archived courses to which the user is assigned appear here. Content can no longer be changed, but stored files can be downloaded as zip files.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '0237ea35a203be81e44c979d82ef5ee6'");
        $db->exec("UPDATE `help_content` SET `content` = 'Here the affiliation to user domains can be viewed, but not changed.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '0e816d9428a3bc8a73fb0042fb2da540'");
        $db->exec("UPDATE `help_content` SET `content` = 'Titles, descriptions, lecturers, etc. can be changed in the basic data. Editing can be partially blocked if data is transferred from other systems (for example, LSF/ UniVZ).', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '615c1887f0ee080043f133681ebf0def'");
        $db->exec("UPDATE `help_content` SET `content` = 'Under \"Study details\", additional study programmes and institutions can be added manually if they have not been transferred automatically from an external system (e.g. LSF/ UniVZ).', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '970ebdf39ad5ca89083a52723c5c35f5'");
        $db->exec("UPDATE `help_content` SET `content` = 'With the institute search, institutions can be found via a free search field or the facility tree.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '8a32ca4e602a68307d4ae6ae51fa667e'");
        $db->exec("UPDATE `help_content` SET `content` = 'On this page you can make sure before archiving that the right course(s) have been selected for archiving.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = 'a2a649de15c8d8473b11fccc731dc80f'");
        $db->exec("UPDATE `help_content` SET `content` = 'Select the desired system and then the learning module/test. Writing permissions determine who can edit the learning module in the future. In the sidebar you will find the option \"Update assignments\" in order to transfer changed contents e.g. in the ILIAS course to Stud.IP.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '8b690f942bf0cc0322e5bea0f1b9abed'");
        $db->exec("UPDATE `help_content` SET `content` = 'Various display and notification options can be selected and changed in the general settings.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = 'c8e789a0efb73f00f00dacf565524c73'");
        $db->exec("UPDATE `help_content` SET `content` = 'With the image uploading feature, the image of a course can be changed, which can help students differentiate between courses on the My Courses page.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = 'abfb5d03de288d02df436f9a8bb96d9d'");
        $db->exec("UPDATE `help_content` SET `content` = 'Here, lecturers can create and display announcements for their courses, institutions, and profile page, with the ability to filter the display.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '3318ee99a062079b463e902348ad520e'");
        $db->exec("UPDATE `help_content` SET `content` = 'The group calendar provides an overview of course dates and personalized additional dates for that course.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '38d1a86517eb6cc195b2e921270c3035'");
        $db->exec("UPDATE `help_content` SET `content` = 'Here you can add and edit dates.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '76195b21d485823fd7ca2fd499131c12'");
        $db->exec("UPDATE `help_content` SET `content` = 'In DoIT!, lecturers have the ability to set different types of tasks, including file uploads, multiple-choice questions, and peer reviewing. The task processing can be limited in time and can be done in groups.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '0838a96b5678e2fc26be0ee38ae67619'");
        $db->exec("UPDATE `help_content` SET `content` = 'Blubber is the Stud.IP real-time forum, a mixture of forum and chat. Others can be informed about a post by mentioning them by @username or @''firstname surname'' in the post. Texts can be formatted and supplemented with smileys.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = 'b9586c280a0092f86f9392fe5b5ff2a0'");
        $db->exec("UPDATE `help_content` SET `content` = 'An overview of sent, internal system messages, which can be provided with self-selected keywords (\"tags\") in order to be able to find them more easily later.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = 'ceb21257092b11dcf6897d5bb3085642'");
        $db->exec("UPDATE `help_content` SET `content` = 'The time/room feature can be used to change the semester, date and room details of the course. Editing can be blocked if data is transferred from other systems (e.g. LSF/ UniVZ).', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '85c709de75085bd56a739e4e8ac6fcad'");
        $db->exec("UPDATE `help_content` SET `content` = 'The reference page offers teachers the possibility to create reference lists or to import them from reference management programs. These lists can be copied into courses and made visible. Depending on the connection, the actual book inventory of the university can be searched.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '44edb997707d1458cbf8a3f8f316b908'");
        $db->exec("UPDATE `help_content` SET `content` = 'Configuration of the study diary for students and creation of a study diary for lecturers.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '2075fe42f56207fbd153a810188f1beb'");
        $db->exec("UPDATE `help_content` SET `content` = 'With the archive search you can search for courses that have already been archived.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '7d40379f54250b550065e062d71e8fd8'");
        $db->exec("UPDATE `help_content` SET `content` = 'The courses page shows all subscribed courses (by default only those of the last two semesters), all subscribed study groups and all institutions to which you have been assigned. The display can be adjusted via colour codes, semester filters, etc.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '91d6f451c3ef8d8352a076773b0a19ee'");
        $db->exec("UPDATE `help_content` SET `content` = 'On this page you can sort contacts into self-defined groups.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '6b331f5cc2176daba82a0cc71aaa576f'");
        $db->exec("UPDATE `help_content` SET `content` = 'The score list sorts the Stud.IP users in descending order according to their score. The number of points increases with the activities in Stud.IP and thus represents the experience of the users with the system. By ticking the box on the left, the own value is made visible to other users in the ranking. By default, your own value is not visible to the public.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '90ffbd715843b02b3961907f81caf208'");
        $db->exec("UPDATE `help_content` SET `content` = 'You can use the administration features to change the properties of the course at a later date. Under Actions a simulation of the student''s view is possible.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '0c055cc6ae418a96ff3afa9db13098df'");
        $db->exec("UPDATE `help_content` SET `content` = 'The profile page allows you to change your own user data including profile picture and categories. Similar to Facebook, comments can be left. The lecturer''s profile contains office hours and room details. In addition, the page offers the management of own files.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = 'e5bff29f7adee43202a2aa8f3f0a6ec7'");
        $db->exec("UPDATE `help_content` SET `content` = 'Here you can create a new study group. Each Stud.IP user can create study groups and configure them according to their own needs.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = 'af7573cce1e898054db89a96284866f9'");
        $db->exec("UPDATE `help_content` SET `content` = 'The settings of the messaging system offer the possibility to forward the messages received in Stud.IP to your email address.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '3b7a4c04017fef2984ee029610194f26'");
        $db->exec("UPDATE `help_content` SET `content` = 'The schedule settings offer the possibility to be adapted to your own needs.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '260ee12fdc7dccb30eca2cc075ef0096'");
        $db->exec("UPDATE `help_content` SET `content` = 'With the course search you can find courses, study groups etc. in different semesters and according to different search criteria (see \"Show advanced search\" in the sidebar). The current semester is preselected.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = 'a1e3da35edc9b605f670e9c7f5019888'");
        $db->exec("UPDATE `help_content` SET `content` = 'The study diary supports the autonomous studying process of the students and is managed independently by them. Inquiries to the lecturers regarding work steps are possible, certain data can be released individually.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '1ea099717ceb1b401aedcedc89814d9c'");
        $db->exec("UPDATE `help_content` SET `content` = 'Here you can edit reference lists and make them visible in the course (by clicking on the \"eye\").', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '1cb8fd77427ebc092d751eea95454b0a'");
        $db->exec("UPDATE `help_content` SET `content` = 'Here, contact groups or the entire address book can be exported in order to import them into an external program.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '57f1b29d3c1a558f5cc799c1aade7f14'");
        $db->exec("UPDATE `help_content` SET `content` = 'Blubber is a mixed version of forum and chat where participants'' posts are displayed in real time. Others can be informed about a post by mentioning them in the post by @username or @''first name last name''.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '1804e526c2f6794b877a4b2096eaa67a'");
        $db->exec("UPDATE `help_content` SET `content` = 'The learning module interface makes it possible to provide study units or tests from external programs such as ILIAS and LON-CAPA in Stud.IP.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '0d83ce036f2870f873446230c0118bb7'");
        $db->exec("UPDATE `help_content` SET `content` = 'The list of participants shows a list of the participants of the course. Additional participants can be added, removed, downgraded, promoted or assigned to self-defined groups by lecturers.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '3607d6daea679dcd7003e076fdd1660a'");
        $db->exec("UPDATE `help_content` SET `content` = 'In the privacy settings you can set the visibility and discoverability of your own profile.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = 'f5e59c4fc98e1df7fe29b8e9320853e7'");
        $db->exec("UPDATE `help_content` SET `content` = 'Before archiving you can check on this page that the right course(s) have been selected for archiving.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = 'a2a649de15c8d8473b11fccc731dc80f'");
        $db->exec("UPDATE `help_content` SET `content` = 'The attendance list shows all course appointments (meeting, lecture, exercise, internship) of the schedule and allows students to be entered by the lecturers in Stud.IP as well as exporting the list to an overview or as a basis for handwritten entries.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '8c2fc90bd8175e6d598f895944a8ddc2'");
        $db->exec("UPDATE `help_content` SET `content` = 'Blubber is a mixture of forum and chat. Messages are displayed in the public stream. Other users can be informed about a post by mentioning them by @username or @''firstname surname'' in the post.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '51a0399250de6365619c961ec3669ad3'");
        $db->exec("UPDATE `help_content` SET `content` = 'File management offers the possibility to upload, link to, manage and download files.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = 'ee91ec0f9085221ada06d171a27d2405'");
        $db->exec("UPDATE `help_content` SET `content` = 'File management provides the ability to upload, manage, and download personal files that are not visible to others.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '51b98d659590e1e37dae5e5e5cc028bb'");
        $db->exec("UPDATE `help_content` SET `content` = 'The learning module interface makes it possible to provide study units from external programs such as ILIAS and LON-CAPA in Stud.IP. A separate user account is created or assigned for each external system. With the appropriate rights, own learning modules can be created.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = 'bfb70d5f036769d740fb2342b0b58183'");
        $db->exec("UPDATE `help_content` SET `content` = 'This page shows the study groups to which the user is assigned. Study groups are an easy way to collaborate with fellow students, colleagues and others. Each user can create study groups or search for them. The colour coding can be adjusted individually.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '02b4e3ce7b8fe6b3e6a3586d410a51a1'");
        $db->exec("UPDATE `help_content` SET `content` = 'The Wiki enables a common, asynchronous creation and editing of texts. Texts can be formatted and linked so that a branched reference guide is created.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '7edc08f2f7b0786ca036f8c448441e07'");
        $db->exec("UPDATE `help_content` SET `content` = 'The message page provides an overview of received, internal system messages, which can be assigned self-selected keywords (\"tags\") to make them easier to find later.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = 'f966e348174927565b94e606bbcf064f'");
        $db->exec("UPDATE `help_content` SET `content` = 'This page allows the storing of free information, links etc.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = 'abaa7b076e6923ac43120f3326322af0'");
        $db->exec("UPDATE `help_content` SET `content` = 'Here, appointments can be assigned topics or previously entered topics can be taken over and edited.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '1f216fe42d879c3fcbb582d67e9ad5a2'");
        $db->exec("UPDATE `help_content` SET `content` = 'Here you can enter predefined information about yourself, that should appear on your profile page.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '83fd70727605c485a0d8f2c5ef94289b'");
        $db->exec("UPDATE `help_content` SET `content` = 'A custom Blubber stream can be created here. It always consists of a collection of posts from selected courses, contact groups and keywords, which can be further restricted by filtering. The new user-defined stream can be found after clicking on the Save button in the navigation under Global Stream.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '7cb7026818c4b90935009d0548300674'");
        $db->exec("UPDATE `help_content` SET `content` = 'By exporting, data about courses and co-workers can be exported into the following formats: RTF, TXT, CSV, PDF, HTML and XML.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '7bf322a6c5f13db67e047b7afae83e58'");
        $db->exec("UPDATE `help_content` SET `content` = 'The password of the Stud.IP account can be changed here.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = 'b32cb2c4ec56e925b07a5cb0105a6888'");
        $db->exec("UPDATE `help_content` SET `content` = 'The self-defined groups are displayed here. Messages can be sent to these groups. A click on the orange arrows in front of the group name assigns you to the group.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = 'f529bca4d1626b43cbb8149feea41a84'");
        $db->exec("UPDATE `help_content` SET `content` = 'The appointment calendar consists of subscribed courses and your own appointments. It can be edited, changed in the display and compared with external programs (e.g. Outlook).', `studip_version` = '4.4' WHERE `help_content`.`content_id` = 'dddf5fd4406da0d91c9f121fcae607ad'");
        $db->exec("UPDATE `help_content` SET `content` = 'This page shows all study groups that exist in Stud.IP. Study groups are an easy way to collaborate with fellow students, colleagues and others. Each user can create study groups or search for them.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '960d7bafb618853eced1b1b42a7dd412'");
        $db->exec("UPDATE `help_content` SET `content` = 'Groups can be created and managed here. If the self-entry is activated, participants can register themselves and sign themselves out.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = 'bd5df4fb7b84da79149c96c5f43de46c'");
        $db->exec("UPDATE `help_content` SET `content` = 'Here you can search for references in catalogues and add them to your list.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = 'b283b58820db358284f4451dfb691678'");
        $db->exec("UPDATE `help_content` SET `content` = 'On this page you can enter self-defined information about yourself, which should appear on the profile page.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '8ad364363acd415631226d5574d5592a'");
        $db->exec("UPDATE `help_content` SET `content` = 'With the Surveys and Tests function, you can create (time-controlled) surveys or individual multiple/single-choice questions for courses, study groups or the profile.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '42060187921376807f90e52fad5f9822'");
        $db->exec("UPDATE `help_content` SET `content` = 'Here you can upload a profile picture.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '2a389c2472656121a76ca4f3b0e137d4'");
        $db->exec("UPDATE `help_content` SET `content` = 'RSS feeds, i.e. news streams from external websites, can be integrated on the start page. The more feeds you include, the longer it takes to load the start page.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = 'bcdedaf1b4bd3b96ef574e8230095b28'");
        $db->exec("UPDATE `help_content` SET `content` = 'The name, function and access restriction of the study group can be edited here.', `studip_version` = '4.4' WHERE `help_content`.`content_id` = '3d040e95a8c29e733a8d5439ee9f5b59'");
    }

    public function down()
    {
    }
}
