<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'ParagonIE\\ConstantTime\\' => array($vendorDir . '/paragonie/constant_time_encoding/src'),
    'OTPHP\\' => array($vendorDir . '/spomky-labs/otphp/src'),
    'Leafo\\ScssPhp\\' => array($vendorDir . '/leafo/scssphp/src'),
    'Assert\\' => array($vendorDir . '/beberlei/assert/lib/Assert'),
);
