#!/bin/bash

#
#  extract all Stud.IP message strings and merge with old translations
#

for language in en;
do {
	# first handle files separate
	mv locale/$language/LC_MESSAGES/studip_core.po locale/$language/LC_MESSAGES/studip_core.po.old
	xgettext -C -n --keyword=_ -o locale/$language/LC_MESSAGES/studip_core.pot  *.php
	msgmerge locale/$language/LC_MESSAGES/studip_core.po.old locale/$language/LC_MESSAGES/studip_core.pot --output-file=locale/$language/LC_MESSAGES/studip_core.po

	# then merge into one file
	msgcat locale/$language/LC_MESSAGES/studip_core.po locale/$language/LC_MESSAGES/studip.po --output-file=locale/$language/LC_MESSAGES/studip.po --use-first
} ;
done
