#!/bin/bash

#
#  extract all Stud.IP message strings and merge with old translations
#

for language in en;
do {
	# first handle files separate
	mv locale/$language/LC_MESSAGES/studip_core.po locale/$language/LC_MESSAGES/studip_core.po.old
	xgettext -C -n --keyword=_ -o locale/$language/LC_MESSAGES/studip_core.pot  *.* lib/classes/*.* lib/classes/auth_plugins/*.* lib/classes/lit_search_plugins/*.* lib/dbviews/*.* help/*.*
	msgmerge locale/$language/LC_MESSAGES/studip_core.po.old locale/$language/LC_MESSAGES/studip_core.pot --output-file=locale/$language/LC_MESSAGES/studip_core.po

	mv locale/$language/LC_MESSAGES/studip_calendar.po locale/$language/LC_MESSAGES/studip_calendar.po.old
	xgettext -C -n --keyword=_ -o locale/$language/LC_MESSAGES/studip_calendar.pot  calendar/*.* calendar/lib/*.* calendar/views/*.* calendar/lib/driver/MySQL/*.* calendar/lib/sync/*.*
	msgmerge locale/$language/LC_MESSAGES/studip_calendar.po.old locale/$language/LC_MESSAGES/studip_calendar.pot --output-file=locale/$language/LC_MESSAGES/studip_calendar.po

	mv locale/$language/LC_MESSAGES/studip_chat.po locale/$language/LC_MESSAGES/studip_chat.po.old
	xgettext -C -n --keyword=_ -o locale/$language/LC_MESSAGES/studip_chat.pot  chat/*.*
	msgmerge locale/$language/LC_MESSAGES/studip_chat.po.old locale/$language/LC_MESSAGES/studip_chat.pot --output-file=locale/$language/LC_MESSAGES/studip_chat.po

	mv locale/$language/LC_MESSAGES/studip_resources.po locale/$language/LC_MESSAGES/studip_resources.po.old
	xgettext -C -n --keyword=_ -o locale/$language/LC_MESSAGES/studip_resources.pot  resources/*.* resources/lib/*.* resources/views/*.*
	msgmerge locale/$language/LC_MESSAGES/studip_resources.po.old locale/$language/LC_MESSAGES/studip_resources.pot --output-file=locale/$language/LC_MESSAGES/studip_resources.po

	mv locale/$language/LC_MESSAGES/studip_export.po locale/$language/LC_MESSAGES/studip_export.po.old
	xgettext -C -n --keyword=_ -o locale/$language/LC_MESSAGES/studip_export.pot  export/*.*
	msgmerge locale/$language/LC_MESSAGES/studip_export.po.old locale/$language/LC_MESSAGES/studip_export.pot --output-file=locale/$language/LC_MESSAGES/studip_export.po

	mv locale/$language/LC_MESSAGES/studip_lernmodule.po locale/$language/LC_MESSAGES/studip_lernmodule.po.old
	xgettext -C -n --keyword=_ -o locale/$language/LC_MESSAGES/studip_lernmodule.pot  lernmodule/*.*
	msgmerge locale/$language/LC_MESSAGES/studip_lernmodule.po.old locale/$language/LC_MESSAGES/studip_lernmodule.pot --output-file=locale/$language/LC_MESSAGES/studip_lernmodule.po

	mv locale/$language/LC_MESSAGES/studip_extern.po locale/$language/LC_MESSAGES/studip_extern.po.old
	xgettext -C -n --keyword=_ -o locale/$language/LC_MESSAGES/studip_extern.pot  extern/*.* extern/views/*.* extern/modules/*.* extern/modules/views/*.* extern/lib/*.* extern/elements/*.* extern/elements/main/*.*
	msgmerge locale/$language/LC_MESSAGES/studip_extern.po.old locale/$language/LC_MESSAGES/studip_extern.pot --output-file=locale/$language/LC_MESSAGES/studip_extern.po

	mv locale/$language/LC_MESSAGES/studip_support.po locale/$language/LC_MESSAGES/studip_support.po.old
	xgettext -C -n --keyword=_ -o locale/$language/LC_MESSAGES/studip_support.pot  support/*.* support/views/*.* support/lib/*.*
	msgmerge locale/$language/LC_MESSAGES/studip_support.po.old locale/$language/LC_MESSAGES/studip_support.pot --output-file=locale/$language/LC_MESSAGES/studip_support.po

	mv locale/$language/LC_MESSAGES/studip_vote.po locale/$language/LC_MESSAGES/studip_vote.po.old
	xgettext -C -n --keyword=_ -o locale/$language/LC_MESSAGES/studip_vote.pot  vote/*.* vote/view/*.*
	msgmerge locale/$language/LC_MESSAGES/studip_vote.po.old locale/$language/LC_MESSAGES/studip_vote.pot --output-file=locale/$language/LC_MESSAGES/studip_vote.po

	mv locale/$language/LC_MESSAGES/studip_wap.po locale/$language/LC_MESSAGES/studip_wap.po.old
	xgettext -C -n --keyword=_ -o locale/$language/LC_MESSAGES/studip_wap.pot  wap/*.* 
	msgmerge locale/$language/LC_MESSAGES/studip_wap.po.old locale/$language/LC_MESSAGES/studip_wap.pot --output-file=locale/$language/LC_MESSAGES/studip_wap.po

	mv locale/$language/LC_MESSAGES/studip_eval.po locale/$language/LC_MESSAGES/studip_eval.po.old
	xgettext -C -n --keyword=_ -o locale/$language/LC_MESSAGES/studip_eval.pot  modules/evaluation/*.* modules/evaluation/classes/*.* modules/evaluation/classes/db/*.*
	msgmerge locale/$language/LC_MESSAGES/studip_eval.po.old locale/$language/LC_MESSAGES/studip_eval.pot --output-file=locale/$language/LC_MESSAGES/studip_eval.po

	# then merge into one file
	msgcat locale/$language/LC_MESSAGES/studip_core.po locale/$language/LC_MESSAGES/studip.po --output-file=locale/$language/LC_MESSAGES/studip.po --use-first
	msgcat locale/$language/LC_MESSAGES/studip_calendar.po locale/$language/LC_MESSAGES/studip.po --output-file=locale/$language/LC_MESSAGES/studip.po --use-first
	msgcat locale/$language/LC_MESSAGES/studip_chat.po locale/$language/LC_MESSAGES/studip.po --output-file=locale/$language/LC_MESSAGES/studip.po --use-first
	msgcat locale/$language/LC_MESSAGES/studip_resources.po locale/$language/LC_MESSAGES/studip.po --output-file=locale/$language/LC_MESSAGES/studip.po --use-first
	msgcat locale/$language/LC_MESSAGES/studip_export.po locale/$language/LC_MESSAGES/studip.po --output-file=locale/$language/LC_MESSAGES/studip.po --use-first
	msgcat locale/$language/LC_MESSAGES/studip_lernmodule.po locale/$language/LC_MESSAGES/studip.po --output-file=locale/$language/LC_MESSAGES/studip.po --use-first
	msgcat locale/$language/LC_MESSAGES/studip_extern.po locale/$language/LC_MESSAGES/studip.po --output-file=locale/$language/LC_MESSAGES/studip.po --use-first
	msgcat locale/$language/LC_MESSAGES/studip_support.po locale/$language/LC_MESSAGES/studip.po --output-file=locale/$language/LC_MESSAGES/studip.po --use-first
	msgcat locale/$language/LC_MESSAGES/studip_vote.po locale/$language/LC_MESSAGES/studip.po --output-file=locale/$language/LC_MESSAGES/studip.po --use-first
	msgcat locale/$language/LC_MESSAGES/studip_wap.po locale/$language/LC_MESSAGES/studip.po --output-file=locale/$language/LC_MESSAGES/studip.po --use-first
	msgcat locale/$language/LC_MESSAGES/studip_eval.po locale/$language/LC_MESSAGES/studip.po --output-file=locale/$language/LC_MESSAGES/studip.po --use-first
} ;
done
