#!/bin/bash

#
#  convert all Stud.IP message strings into binary format
#

for language in en;
do {
	mv locale/$language/LC_MESSAGES/studip.mo locale/$language/LC_MESSAGES/studip.mo.old
	msgfmt locale/$language/LC_MESSAGES/studip.po --output-file=locale/$language/LC_MESSAGES/studip.mo
} ;
done
