#!/bin/sh

#
#  STEP 1:
#  extract all Stud.IP message strings and merge them with the existing translations
#

LOCALE_RELATIVE_PATH="../public/locale"
TRANSLATIONFILES_RELAVITVE_PATHS="../public ../lib"

for language in en
do
	test -f "$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/studip.po" && mv "$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/studip.po" "$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/studip.po.old"
	> "$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/studip.pot"
	find $TRANSLATIONFILES_RELAVITVE_PATHS -iname "*.php" | xargs xgettext -C -j -n --from-code=ISO-8859-1 --keyword=_ -o "$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/studip.pot"
	test -f "$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/studip.po.old" && msgmerge "$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/studip.po.old" "$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/studip.pot" --output-file="$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/studip.po"
done